{% set name = "hspf_reader" %}
{% set version = "2.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hspf_reader-{{ version }}.tar.gz
  sha256: 0aee1da85cd39e899ba2ae38dd31f3a156d9a8ac898cfb73dfc57113a6da643f

build:
  entry_points:
    - hspf_reader = hspf_reader.hspf_reader:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
    - pip
  run:
    - cltoolbox >=2.0.0,<3.0.0
    - dateparser
    - matplotlib-base >=3.3.2
    - numpy
    - openpyxl >=3.0.7
    - odfpy >=1.4.1
    - pandas
    - pint !=0.21
    - pint-pandas
    - pydantic
    - python >=3.8
    - pytables >=3.6.1
    - pyxlsb >=1.0.8
    - scipy
    - tabulate
    - typing-extensions
    - xlrd >=2.0.1
    - xlsxwriter

test:
  imports:
    - hspf_reader
  commands:
    - pip check
    - hspf_reader --help
  requires:
    - pip

about:
  summary: Command line script and Python library to read HSPF WDM, binary, and plotgen time series.
  home: https://pypi.org/project/hspf-reader/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
