{% set name = "hspf_reader" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/hspf_reader-{{ version }}.tar.gz
  sha256: 1b03f3a24028335935776ccf0a2787d64318a6b13a1fb14c4ad65b57fa711dba

build:
  entry_points:
    - hspf_reader = hspf_reader.hspf_reader:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=45
    - setuptools-scm >=6.2
    - wheel
    - pip
  run:
    - python >=3.8
    - cltoolbox >=2.0.0,<3.0.0
    - typing-extensions
    - toolbox_utils >=5.0.0,<6.0.0
    - numpy
    - pandas

test:
  imports:
    - hspf_reader
  commands:
    - pip check
    - hspf_reader --help
  requires:
    - pip

about:
  summary: Command line script and Python library to read HSPF WDM, binary, and plotgen time series.
  home: https://pypi.org/project/hspf-reader/
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - timcera
